In [47]:
import pandas as pd 
boys = pd.read_html("https://en.wikipedia.org/wiki/List_of_Trailer_Park_Boys_episodes#Season_1_(2001)")
boys[0]
seasons_info = pd.DataFrame(data=boys[0])
blankindex=[""]*len(seasons_info)
seasons_info.index=blankindex
seasons_info

 Season Episodes              Originally aired
 Season Episodes Episodes.1        First aired         Last aired   Network
      1        6          6     April 22, 2001       May 27, 2001  Showcase
      2        7          7      June 23, 2002     August 4, 2002  Showcase
      3        8          8     April 20, 2003       June 8, 2003  Showcase
      4        8          8     April 11, 2004       May 30, 2004  Showcase
      5       10         10     April 17, 2005      June 19, 2005  Showcase
      6        6          6     April 16, 2006       May 21, 2006  Showcase
      7       10         10      April 8, 2007      June 10, 2007  Showcase
      8       10         10  September 5, 2014  September 5, 2014   Netflix
      9       10         10     March 27, 2015     March 27, 2015   Netflix
     10       10         10     March 25, 2016     March 25, 2016   Netflix
     11       10         10     March 31, 2017     March 31, 2017   Netflix
     12       10         10     March 30, 2018     March 30, 2018   Netflix
     13       10         10    January 1, 2021      March 4, 2021  Swearnet